package com.chave.config;

import com.chave.pojo.RuleItem;

import java.util.ArrayList;

public class SensitiveInfoConfig {
    public static Boolean IS_CHECK_SENSITIVE_INFO = Boolean.FALSE;
    public static String RULE_CONFIG_DIR =  System.getProperty("os.name").toLowerCase().contains("win") ? System.getProperty("user.home") + "\\.config\\API-Highlighter\\" : System.getProperty("user.home") + "/.config/API-Highlighter/";
    public static String RULE_CONFIG_FILE = System.getProperty("os.name").toLowerCase().contains("win") ? System.getProperty("user.home") + "\\.config\\API-Highlighter\\Rules.yml" : System.getProperty("user.home") + "/.config/API-Highlighter/Rules.yml";
    public static String DEFAULT_RULE_LIST_DATA = "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAAKdwQAAAAKc3IAF2NvbS5jaGF2ZS5wb2pvLlJ1bGVJdGVtdqK4luS3hqYCAARMAAZsb2FkZWR0ABNMamF2YS9sYW5nL0Jvb2xlYW47TAAEbmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wABXJlZ2V4cQB+AARMAAVzY29wZXEAfgAEeHBzcgARamF2YS5sYW5nLkJvb2xlYW7NIHKA1Zz67gIAAVoABXZhbHVleHABdAAFRW1haWx0AGEoKFthLXowLTldW198XC5dKSpbYS16MC05XStAKFthLXowLTldWy18X3xcLl0pKlthLXowLTldK1wuKCg/IWpzfGNzc3xqcGd8anBlZ3xwbmd8aWNvKVthLXpdezIsfSkpdAAIcmVzcG9uc2VzcQB+AAJxAH4AB3QADkNoaW5lc2UgSURDYXJkdAB8W14wLTldKChcZHs4fSgwXGR8MTB8MTF8MTIpKFswLTJdXGR8MzB8MzEpXGR7M30kKXwoXGR7Nn0oMTh8MTl8MjApXGR7Mn0oMFsxLTldfDEwfDExfDEyKShbMC0yXVxkfDMwfDMxKVxkezN9KFxkfFh8eCkpKVteMC05XXQACHJlc3BvbnNlc3EAfgACcQB+AAd0ABVDaGluZXNlIE1vYmlsZSBOdW1iZXJ0AHRbXlx3XSgoPzooPzpcK3wwMCk4Nik/MSg/Oig/OjNbXGRdKXwoPzo0WzUtNzldKXwoPzo1WzAtMzUtOV0pfCg/OjZbNS03XSl8KD86N1swLThdKXwoPzo4W1xkXSl8KD86OVsxODldKSlcZHs4fSlbXlx3XXQACHJlc3BvbnNlc3EAfgACcQB+AAd0ABNJbnRlcm5hbCBJUCBBZGRyZXNzdACFW14wLTldKCgxMjdcLjBcLjBcLjEpfCgxMFwuXGR7MSwzfVwuXGR7MSwzfVwuXGR7MSwzfSl8KDE3MlwuKCgxWzYtOV0pfCgyXGQpfCgzWzAxXSkpXC5cZHsxLDN9XC5cZHsxLDN9KXwoMTkyXC4xNjhcLlxkezEsM31cLlxkezEsM30pKXQACHJlc3BvbnNlc3EAfgACcQB+AAd0ABRDaGluZXNlIEJhbmsgQ2FyZCBJRHQAHFteMC05XShbMS05XVxkezEyLDE4fSlbXjAtOV10AAhyZXNwb25zZXNxAH4AAnEAfgAHdAAJQ2xvdWQgS2V5dAA3KChhY2Nlc3NrZXlpZCl8KGFjY2Vzc2tleXNlY3JldCl8KExUQUlbYS16MC05XXsxMiwyMH0pKXQAA2FueXNxAH4AAnEAfgAHdAAOUGFzc3dvcmQgRmllbGR0AEUoKHwnfCIpKFtwXShhc3N8d2R8YXNzd2R8YXNzd29yZCkpKHwnfCIpKDp8PSkoIHwpKCd8IikoLio/KSgnfCIpKHwsKSl0AAhyZXNwb25zZXNxAH4AAnEAfgAHdAAOVXNlcm5hbWUgRmllbGR0AFEoKHwnfCIpKChbdV0oc2VyfG5hbWV8YW1lfHNlcm5hbWUpKXwoYWNjb3VudCkpKHwnfCIpKDp8PSkoIHwpKCd8IikoLio/KSgnfCIpKHwsKSl0AAhyZXNwb25zZXNxAH4AAnEAfgAHdAAPSkRCQyBDb25uZWN0aW9udAAnKGpkYmM6W2EtejpdKzovL1thLXowLTlcLlwtXzo7PS9APywmXSspdAADYW55c3EAfgACcQB+AAd0AA9TZW5zaXRpdmUgRmllbGR0AG4oKHwnfCIpKFtcd117MCwxMH0pKChrZXkpfChzZWNyZXQpfCh0b2tlbil8KGNvbmZpZyl8KGF1dGgpfChhY2Nlc3MpfChhZG1pbikpKHwnfCIpKDp8PSkofCkoJ3wiKSguKj8pKCd8IikofCwpKXQACHJlc3BvbnNleA==";

    public static ArrayList<RuleItem> RULE_LIST;
}
